version: '3'

services:
    app:
        build:
            context: .
        image: "filamentblog"
        ports:
            - "80:80"
        volumes:
            - .:/app
            - ./Caddyfile:/etc/caddy/Caddyfile
