version: '3'

services:
    app:
        build:
            context: .
        image: "filamentblog"
        ports:
            - "80:80"
        environment:
          SERVER_NAME: ":80"
        volumes:
            - .:/app
            - ./default.Caddyfile:/etc/caddy/Caddyfile
