---
- name: Deploy latest main branch
  hosts: production
  become: no
  vars_files:
    - var.yaml

  tasks:
    - name: pull latest image
      ansible.builtin.shell: |
        docker pull jhonoryza/filament-blog:{{ tag }}

    - name: up service
      ansible.builtin.shell: |
        cd {{ deployDir }}
        docker compose -f production.docker-compose.yaml up -d
        docker image prune -f
        docker builder prune --force

    - name: optimize app
      ansible.builtin.shell: |
        docker exec app php artisan filament:cache-components
        docker exec app php artisan icons:cache
